add API checking

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -15,3 +15,35 @@ jobs:
         run: |
           echo "Deploying the application..."
           echo "Deployment completed."
+
+  test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+
+      # Backend
+      - name: Start Backend Server
+        run: |
+          cd backend
+          nohup npm start &
+          sleep 10
+          echo "Backend server started"
+
+      - name: Test Backend API
+        run: |
+          curl -f http://localhost:5000 || (echo "Backend API test failed" && exit 1)
+          echo "Backend API is working!"
+
+      # Frontend
+      - name: Start Frontend Server
+        run: |
+          cd frontend
+          nohup npm run dev &
+          sleep 10
+          echo "Frontend server started"
+
+      - name: Test Frontend API
+        run: |
+          curl -f http://localhost:5173 || (echo "Frontend API test failed" && exit 1)
+          echo "Frontend API is working!"
