fixes

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -16,35 +16,41 @@ jobs:
           echo "Deploying the application..."
           echo "Deployment completed."
 
-  # test-api:
-  #   runs-on: ubuntu-latest
-  #   needs: [backend, frontend]
+  test-api:
+    runs-on: ubuntu-latest
+    needs: [backend, frontend]
 
-  #   steps:
-  #     - uses: actions/checkout@v3
+    steps:
+      - uses: actions/checkout@v3
 
-  #     # Backend
-  #     - name: Start Backend Server
-  #       run: |
-  #         cd backend
-  #         nohup npm start &
-  #         sleep 10
-  #         echo "Backend server started"
+      # Backend
+      - name: Install Backend Dependencies
+        run: cd backend && npm i
 
-  #     - name: Test Backend API
-  #       run: |
-  #         curl -f http://localhost:5000 || (echo "Backend API test failed" && exit 1)
-  #         echo "Backend API is working!"
+      - name: Start Backend Server
+        run: |
+          cd backend
+          nohup npm start &
+          sleep 10
+          echo "Backend server started"
 
-  #     # Frontend
-  #     - name: Start Frontend Server
-  #       run: |
-  #         cd frontend
-  #         nohup npm run dev &
-  #         sleep 10
-  #         echo "Frontend server started"
+      - name: Test Backend API
+        run: |
+          curl -f http://localhost:5000 || (echo "Backend API test failed" && exit 1)
+          echo "Backend API is working!"
 
-  #     - name: Test Frontend API
-  #       run: |
-  #         curl -f http://localhost:5173 || (echo "Frontend API test failed" && exit 1)
-  #         echo "Frontend API is working!"
+      # Frontend
+      - name: Install Frontend Dependencies
+        run: cd frontend && npm i
+
+      - name: Start Frontend Server
+        run: |
+          cd frontend
+          nohup npm run dev &
+          sleep 10
+          echo "Frontend server started"
+
+      - name: Test Frontend API
+        run: |
+          curl -f http://localhost:5173 || (echo "Frontend API test failed" && exit 1)
+          echo "Frontend API is working!"
